CREATE TABLE tokens (
    id SERIAL PRIMARY KEY,
    position SMALLINT NOT NULL,
    identifier varchar(64) NOT NULL,
    owner varchar(64) NOT NULL,
    data_contract_id int NOT NULL references data_contracts(id),
    decimals smallint NOT NULL,
    max_supply bigint DEFAULT NULL,
    base_supply bigint NOT NULL,
    localizations jsonb DEFAULT NULL,
    keeps_transfer_history BOOLEAN NOT NULL,
    keeps_freezing_history BOOLEAN NOT NULL,
    keeps_minting_history BOOLEAN NOT NULL,
    keeps_burning_history BOOLEAN NOT NULL,
    keeps_direct_pricing_history BOOLEAN NOT NULL,
    keeps_direct_purchase_history BOOLEAN NOT NULL,
    distribution_rules jsonb DEFAULT NULL,
    mintable BOOLEAN NOT NULL,
    burnable BOOLEAN NOT NULL,
    freezable BOOLEAN NOT NULL,
    unfreezable BOOLEAN NOT NULL,
    destroyable BOOLEAN NOT NULL,
    allowed_emergency_actions BOOLEAN NOT NULL
);