name-template: '$RESOLVED_VERSION 🎉'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: 'API'
    label: 'backend'
  - title: 'Frontend'
    label: 'frontend'
  - title: 'Indexer'
    label: 'indexer'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES