const BatchEnum = {
  DocumentCreateTransition: 0,
  DocumentReplaceTransition: 1,
  DocumentDeleteTransition: 2,
  DocumentTransferTransition: 3,
  DocumentUpdatePriceTransition: 4,
  DocumentPurchaseTransition: 5,
  TokenBurnTransition: 6,
  TokenMintTransition: 7,
  TokenTransferTransition: 8,
  TokenFreezeTransition: 9,
  TokenUnfreezeTransition: 10,
  TokenDestroyFrozenFundsTransition: 11,
  TokenClaimTransition: 12,
  TokenEmergencyActionTransition: 13,
  TokenConfigUpdateTransition: 14,
  TokenDirectPurchaseTransition: 15,
  TokenSetPriceForDirectPurchaseTransition: 16,
  0: 'DocumentCreateTransition',
  1: 'DocumentReplaceTransition',
  2: 'DocumentDeleteTransition',
  3: 'DocumentTransferTransition',
  4: 'DocumentUpdatePriceTransition',
  5: 'DocumentPurchaseTransition',
  6: 'TokenBurnTransition',
  7: 'TokenMintTransition',
  8: 'TokenTransferTransition',
  9: 'TokenFreezeTransition',
  10: 'TokenUnfreezeTransition',
  11: 'TokenDestroyFrozenFundsTransition',
  12: 'TokenClaimTransition',
  13: 'TokenEmergencyActionTransition',
  14: 'TokenConfigUpdateTransition',
  15: 'TokenDirectPurchaseTransition',
  16: 'TokenSetPriceForDirectPurchaseTransition'
}

module.exports = BatchEnum
