const StateTransitionEnum = {
  DATA_CONTRACT_CREATE: 0,
  BATCH: 1,
  IDENTITY_CREATE: 2,
  IDENTITY_TOP_UP: 3,
  DATA_CONTRACT_UPDATE: 4,
  IDENTITY_UPDATE: 5,
  IDENTITY_CREDIT_WITHDRAWAL: 6,
  IDENTITY_CREDIT_TRANSFER: 7,
  MASTERNODE_VOTE: 8,
  0: 'DATA_CONTRACT_CREATE',
  1: 'BATCH',
  2: 'IDENTITY_CREATE',
  3: 'IDENTITY_TOP_UP',
  4: 'DATA_CONTRACT_UPDATE',
  5: 'IDENTITY_UPDATE',
  6: 'IDENTITY_CREDIT_WITHDRAWAL',
  7: 'IDENTITY_CREDIT_TRANSFER',
  8: 'MASTERNODE_VOTE'
}

module.exports = StateTransitionEnum
