export const TokenTransitionEnum = {
  0: 'TOKEN_BURN',
  1: 'TOKEN_MINT',
  2: 'TOKEN_TRANSFER',
  3: 'TOKEN_FREEZE',
  4: 'TOKEN_UNFREEZE',
  5: 'TOKEN_DESTROY_FROZEN_FUNDS',
  6: 'TOKEN_CLAIM',
  7: 'TOKEN_EMERGENCY_ACTION',
  8: 'TOKEN_CONFIG_UPDATE',
  9: 'TOKEN_DIRECT_PURCHASE',
  10: 'TOKEN_SET_PRICE_FOR_DIRECT_PURCHASE'
}
