name: Release

on:
  push:
    tags:        
      - 'v*'
  workflow_run:
    workflows: ["Build and push packages"]
    branches: [main]
    types: 
      - completed

jobs: 
  create_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@v1.3.4
      with:
        ref: ${{ github.ref }}
        check-name: 'deploy'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10

    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create a GitHub release
      uses: release-drafter/release-drafter@v6
      with:
        version: ${{steps.tag.outputs.tag}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}