name: Release

on:
  workflow_run:
    workflows: ["Build and push packages"]
    branches:
      - '*.*.*'
    types:
      - completed

jobs:
  create_tag:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success'
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create a GitHub release
      uses: release-drafter/release-drafter@v6
      with:
        version: ${{ steps.previoustag.outputs.tag }}
        publish: 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
